spring:
  application:
    name: config-server
  # 配置仓库的分支
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/csmervyn/config-repo.git  # 配置git仓库地址ַ
          searchPaths: config-repo  # 配置仓库路径
# username 访问git仓库的用户名 如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写
# password  访问git仓库的用户密码

server:
  port: 8770

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

